version: "3.3"
services:
  back:
    build: .
    restart: always
    links:
      - pg:pg
    depends_on:
      - pg
    ports:
      - 80:8000

  pg:
    image: postgres:12
    restart: always
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
